services:
  frontend:
    build:
      context: ./builds/angular/
    command: 
      - npm 
      - start
    working_dir: /app
    volumes:
      - ./src/frontend:/app
    ports:
      - 4200:4200

  backend:
    build:
      context: ./builds/nestjs/
    command: ['npm', 'start']
    working_dir: /app
    volumes:
      - ./src/backend:/app
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_USER=admin
      - MONGO_PASSWORD=123
  db:
    build:
      context: ./builds/mongo
    environment:
      - USER=admin
      - PASSWORD=123